CLEANED_BRAND_NAMES = {
    "Alfa-romeo": "Alfa Romeo",
    "Great": "Great Wall",
    "Jac": "JAC",
    "Bmw": "BMW",
    "Gmc": "GMC",
    "Byd": "BYD",
    "Gac": "GAC",
    "Mg": "MG",
    "Dfsk": "DFSK",
    "Ssangyong": "SsangYong",
    "Aston": "Aston Martin",
    "Seat": "SEAT",
    "Baic": "BAIC",
    "Mc": "MC",
    "Faw": "FAW",
    "Jmc": "JMC"

}

BRAND_PREMIUM_STATUS = {
    'Ram': 'Normal Brand',
    'Jetour': 'Chinese Brand',
    'Fiat': 'Normal Brand',
    'Volkswagen': 'Normal Brand',
    'Skoda': 'Normal Brand',
    'MG': 'Normal Brand',
    'Jaguar': 'Premium Brand',
    'Alfa Romeo': 'Premium Brand',
    'GMC': 'Normal Brand',
    'Honda': 'Normal Brand',
    'Lexus': 'Premium Brand',
    'BYD': 'Chinese Brand',
    'Maserati': 'Premium Brand',
    'Porsche': 'Premium Brand',
    'Suzuki': 'Normal Brand',
    'Isuzu': 'Normal Brand',
    'Joylong': 'Chinese Brand',
    'Gonow': 'Chinese Brand',
    'Harley': 'Normal Brand',
    'Haval': 'Chinese Brand',
    'Chevrolet': 'Normal Brand',
    'Rover': 'Normal Brand',
    'Mercedes': 'Premium Brand',
    'Daewoo': 'Normal Brand',
    'Kyc': 'Chinese Brand',
    'Kama': 'Normal Brand',
    'Jeep': 'Normal Brand',
    'Kaiyi': 'Chinese Brand',
    'Nissan': 'Normal Brand',
    'Lamborghini': 'Premium Brand',
    'Acura': 'Normal Brand',
    'Samsung': 'Normal Brand',
    'DFSK': 'Chinese Brand',
    'International': 'Normal Brand',
    'Renault': 'Normal Brand',
    'Geely': 'Chinese Brand',
    'Dodge': 'Normal Brand',
    'Toyota': 'Normal Brand',
    'Datsun': 'Normal Brand',
    'Citroen': 'Normal Brand',
    'GAC': 'Chinese Brand',
    'MC': 'Chinese Brand',
    'Jinbei': 'Chinese Brand',
    'Buick': 'Normal Brand',
    'Mahindra': 'Normal Brand',
    'Victory': 'Normal Brand',
    'Cupra': 'Normal Brand',
    'Dongfeng': 'Chinese Brand',
    'Shineray': 'Chinese Brand',
    'FAW': 'Chinese Brand',
    'Pontiac': 'Normal Brand',
    'Land': 'Normal Brand',
    'Changan': 'Chinese Brand',
    'Lifan': 'Chinese Brand',
    'BMW': 'Premium Brand',
    'Chery': 'Chinese Brand',
    'Austin': 'Normal Brand',
    'Audi': 'Premium Brand',
    'Mazda': 'Normal Brand',
    'BAIC': 'Chinese Brand',
    'Daihatsu': 'Normal Brand',
    'Hyundai': 'Normal Brand',
    'Foton': 'Chinese Brand',
    'JMC': 'Chinese Brand',
    'SsangYong': 'Normal Brand',
    'JAC': 'Chinese Brand',
    'Peugeot': 'Normal Brand',
    'Zotye': 'Chinese Brand',
    'Great Wall': 'Chinese Brand',
    'Oldsmobile': 'Normal Brand',
    'Brilliance': 'Chinese Brand',
    'Maxus': 'Chinese Brand',
    'Subaru': 'Normal Brand',
    'Ford': 'Normal Brand',
    'Lada': 'Normal Brand',
    'Soueast': 'Chinese Brand',
    'Chrysler': 'Normal Brand',
    'Mitsubishi': 'Normal Brand',
    'Mini': 'Premium Brand',
    'SEAT': 'Normal Brand',
    'Kia': 'Normal Brand',
    'Aston Martin': 'Premium Brand',
    'Volvo': 'Premium Brand',
}

BRANDS_COUNTRY_CONTINENT = {
    'Ram': {'country': 'USA', 'continent': 'North America'},
    'Jetour': {'country': 'China', 'continent': 'Asia'},
    'Fiat': {'country': 'Italy', 'continent': 'Europe'},
    'Volkswagen': {'country': 'Germany', 'continent': 'Europe'},
    'Skoda': {'country': 'Czech Republic', 'continent': 'Europe'},
    'MG': {'country': 'United Kingdom', 'continent': 'Europe'},
    'Jaguar': {'country': 'United Kingdom', 'continent': 'Europe'},
    'Alfa Romeo': {'country': 'Italy', 'continent': 'Europe'},
    'GMC': {'country': 'USA', 'continent': 'North America'},
    'Honda': {'country': 'Japan', 'continent': 'Asia'},
    'Lexus': {'country': 'Japan', 'continent': 'Asia'},
    'BYD': {'country': 'China', 'continent': 'Asia'},
    'Maserati': {'country': 'Italy', 'continent': 'Europe'},
    'Porsche': {'country': 'Germany', 'continent': 'Europe'},
    'Suzuki': {'country': 'Japan', 'continent': 'Asia'},
    'Isuzu': {'country': 'Japan', 'continent': 'Asia'},
    'Joylong': {'country': 'China', 'continent': 'Asia'},
    'Gonow': {'country': 'China', 'continent': 'Asia'},
    'Harley': {'country': 'USA', 'continent': 'North America'},
    'Haval': {'country': 'China', 'continent': 'Asia'},
    'Chevrolet': {'country': 'USA', 'continent': 'North America'},
    'Rover': {'country': 'United Kingdom', 'continent': 'Europe'},
    'Mercedes': {'country': 'Germany', 'continent': 'Europe'},
    'Daewoo': {'country': 'South Korea', 'continent': 'Asia'},
    'Kyc': {'country': 'China', 'continent': 'Asia'},
    'Kama': {'country': 'Russia', 'continent': 'Europe'},
    'Jeep': {'country': 'USA', 'continent': 'North America'},
    'Kaiyi': {'country': 'China', 'continent': 'Asia'},
    'Nissan': {'country': 'Japan', 'continent': 'Asia'},
    'Lamborghini': {'country': 'Italy', 'continent': 'Europe'},
    'Acura': {'country': 'Japan', 'continent': 'Asia'},
    'Samsung': {'country': 'South Korea', 'continent': 'Asia'},
    'DFSK': {'country': 'China', 'continent': 'Asia'},
    'International': {'country': 'USA', 'continent': 'North America'},
    'Renault': {'country': 'France', 'continent': 'Europe'},
    'Geely': {'country': 'China', 'continent': 'Asia'},
    'Dodge': {'country': 'USA', 'continent': 'North America'},
    'Toyota': {'country': 'Japan', 'continent': 'Asia'},
    'Datsun': {'country': 'Indonesia', 'continent': 'Asia'},
    'Citroen': {'country': 'France', 'continent': 'Europe'},
    'GAC': {'country': 'China', 'continent': 'Asia'},
    'MC': {'country': 'China', 'continent': 'Asia'},
    'Jinbei': {'country': 'China', 'continent': 'Asia'},
    'Buick': {'country': 'USA', 'continent': 'North America'},
    'Mahindra': {'country': 'India', 'continent': 'Asia'},
    'Victory': {'country': 'USA', 'continent': 'North America'},
    'Cupra': {'country': 'Spain', 'continent': 'Europe'},
    'Dongfeng': {'country': 'China', 'continent': 'Asia'},
    'Shineray': {'country': 'China', 'continent': 'Asia'},
    'FAW': {'country': 'China', 'continent': 'Asia'},
    'Pontiac': {'country': 'USA', 'continent': 'North America'},
    'Land': {'country': 'United Kingdom', 'continent': 'Europe'},
    'Changan': {'country': 'China', 'continent': 'Asia'},
    'Lifan': {'country': 'China', 'continent': 'Asia'},
    'BMW': {'country': 'Germany', 'continent': 'Europe'},
    'Chery': {'country': 'China', 'continent': 'Asia'},
    'Austin': {'country': 'United Kingdom', 'continent': 'Europe'},
    'Audi': {'country': 'Germany', 'continent': 'Europe'},
    'Mazda': {'country': 'Japan', 'continent': 'Asia'},
    'BAIC': {'country': 'China', 'continent': 'Asia'},
    'Daihatsu': {'country': 'Japan', 'continent': 'Asia'},
    'Hyundai': {'country': 'South Korea', 'continent': 'Asia'},
    'Foton': {'country': 'China', 'continent': 'Asia'},
    'JMC': {'country': 'China', 'continent': 'Asia'},
    'SsangYong': {'country': 'South Korea', 'continent': 'Asia'},
    'JAC': {'country': 'China', 'continent': 'Asia'},
    'Peugeot': {'country': 'France', 'continent': 'Europe'},
    'Zotye': {'country': 'China', 'continent': 'Asia'},
    'Great Wall': {'country': 'China', 'continent': 'Asia'},
    'Oldsmobile': {'country': 'USA', 'continent': 'North America'},
    'Brilliance': {'country': 'China', 'continent': 'Asia'},
    'Maxus': {'country': 'China', 'continent': 'Asia'},
    'Subaru': {'country': 'Japan', 'continent': 'Asia'},
    'Ford': {'country': 'USA', 'continent': 'North America'},
    'Lada': {'country': 'Russia', 'continent': 'Europe'},
    'Soueast': {'country': 'China', 'continent': 'Asia'},
    'Chrysler': {'country': 'USA', 'continent': 'North America'},
    'Mitsubishi': {'country': 'Japan', 'continent': 'Asia'},
    'Mini': {'country': 'United Kingdom', 'continent': 'Europe'},
    'SEAT': {'country': 'Spain', 'continent': 'Europe'},
    'Kia': {'country': 'South Korea', 'continent': 'Asia'},
    'Aston Martin': {'country': 'United Kingdom', 'continent': 'Europe'},
    'Volvo': {'country': 'Sweden', 'continent': 'Europe'},
}
